### ISSUE TITLE
[ERROR] Java language support requires Java 8

### ISSUE THREAD

**Issue by linfx7** [georgewfraser/vscode-javac#8]
Encontered error message while opening java files. And it didn't work.

Here is the full error message:
> Java language support requires Java 8 (using c:\Program Files\Java\jdk1.8.0_92\bin\java.exe)

I'm using Windows 10 x64 with jdk 1.8. "c:\Program Files\Java\jdk1.8.0_92\" is the root directory of jdk.

**Comment by georgewfraser** [comment]
Can you show me the output when you run

> java -version

in a terminal?

**Comment by linfx7** [comment]
`java -version`
> java version "1.8.0_92"
> Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
> Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)

`javac -version`
> javac 1.8.0_92

**Comment by semornas** [comment]
Hi,
Same issue on my computer (Windows 10 x64)
`java -version`
> java version "1.8.0_91"
> Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
> Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

**Comment by ecmel** [comment]
Sam issue, VS Code version 1.1.1

**Comment by georgewfraser** [comment]
Fixed with v0.0.14

**Comment by SimpleCookie** [comment]
Actually the issue is still there. Just tried with ´version 0.18.1´
